service: meuPoliticoDeEstimacao-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  endpointType: regional
  environment: ${file(src/shared/infra/http/config/serverless/env/${self:provider.stage}.yml)}

  iamRoleStatements:
    # proposition/politician table
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DB_TABLE}'

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  dynamo-table: ${self:custom.prefix}-table

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migration:
        dir: 'src/shared/infra/http/config/serverless/migration'
      convertEmptyValues: true
      inMemory: true
      seed: true
      migrate: true
    seed:
      dev:
        sources:
          - table: ${self:custom.dynamo-table}
            sources: [src/shared/infra/dynamodb/fullSeed.json]

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dynamodb-local

resources: ${file(src/shared/infra/http/config/serverless/resources.yml)}

functions: ${file(src/shared/infra/http/config/serverless/functions.yml)}
