ping:
  handler: src/shared/infra/http/controllers/testController.ping
  description: Test API reachability
  events:
    - http:
        path: ping
        method: get
        cors:
          origin: '*'
addUser:
  handler: src/modules/user/controllers/CreateUserController.addUser
  description: Add User
  events:
    - http:
        path: users
        method: post
        cors:
          origin: '*'
getUser:
  handler: src/modules/user/controllers/GetUserController.getUser
  description: Get User
  events:
    - http:
        path: users/{name}
        method: get
        request:
          parameters:
            paths:
              name: true
        cors:
          origin: '*'
rankThemes:
  handler: src/modules/user/controllers/RankThemesController.rankThemes
  description: Rank themes
  events:
    - http:
        path: users/{id}/themes
        method: post
        cors:
          origin: '*'
        request:
          parameters:
            paths:
              id: true
followPoliticians:
  handler: src/modules/user/controllers/FollowPoliticiansController.followPoliticians
  description: Post FollowPoliticians
  events:
    - http:
        path: users/{id}/politicians
        method: post
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
getUserAndFollowedPoliticians:
  handler: src/modules/user/controllers/GetUserAndFollowedPoliticiansController.getUserAndFollowedPoliticians
  description: GET GetUserAndFollowedPoliticians
  events:
    - http:
        path: users/{id}/politicians
        method: get
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
getThemeAndNewestPropositions:
  handler: src/modules/theme/controllers/GetThemeAndNewestPropositionsController.getThemeAndNewestPropositions
  description: Get ThemeAndNewestPropositions
  events:
    - http:
        path: themes/{id}/proposition
        method: get
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
listThemes:
  handler: src/modules/theme/controllers/ListThemesController.listThemes
  description: List themes
  events:
    - http:
        path: themes
        method: get
        cors:
          origin: '*'
getPropositionAndListAuthors:
  handler: src/modules/proposition/controllers/GetPropositionAndListAuthorsController.getPropositionAndListAuthors
  description: Get PropositionAndListAuthors
  events:
    - http:
        path: propositions/{id}/authors
        method: get
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
listPropositionByAuthor:
  handler: src/modules/politician/controllers/ListPropositionByAuthorController.listPropositionByAuthor
  description: List PropositionByAuthor
  events:
    - http:
        path: politicians/{id}/propositions
        method: get
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
listThemesByAuthor:
  handler: src/modules/politician/controllers/ListThemesByAuthorController.listThemesByAuthor
  description: List ThemesByAuthor
  events:
    - http:
        path: politicians/{id}/themes
        method: get
        request:
          parameters:
            paths:
              id: true
        cors:
          origin: '*'
listRelevantPoliticiansByTheme:
  handler: src/modules/politician/controllers/ListRelevantPoliticiansByThemeController.listRelevantPoliticiansByTheme
  description: List relevant politicians by theme
  events:
    - http:
        path: themes/authors
        method: get
        request:
          parameters:
            querystrings:
              first: true
              second: true
              third: true
        cors:
          origin: '*'
