ping:
  handler: src/shared/infra/http/controllers/testController.ping
  description: Test API reachability
  events:
    - http:
        path: ping
        method: get
        cors:
          origin: '*'
addUser:
  handler: src/modules/user/controllers/CreateUserController.addUser
  description: Add User
  events:
    - http:
        path: users
        method: post
        cors:
          origin: '*'
getUser:
  handler: src/modules/user/controllers/GetUserController.getUser
  description: Get User
  events:
    - http:
        path: users/{name}
        method: get
        request:
          parameters:
            paths:
              name: true
        cors:
          origin: '*'
